import { NextRequest, NextResponse } from "next/server"
import { auth } from "@clerk/nextjs/server"
import { getDatabase, reports, users, insights } from "@/lib/db"
import { eq, and } from "drizzle-orm"
import type { InsightSection } from "@/types"
import { SECTION_METADATA } from "@/types"
import type { InsightContentInput } from "@/lib/insights/schema"

export const dynamic = "force-dynamic"

const SECTION_ORDER: InsightSection[] = [
  "core_identity", "signature_pattern",
  "productivity_style", "decision_making", "daily_actions", "career_alignment",
  "communication_style", "collaboration_style", "leadership", "relationships",
  "blind_spots", "stress_patterns", "work_environment", "growth_opportunities",
]

const ACTION_LABELS: Record<string, string> = {
  today: "Today", this_week: "This week", this_quarter: "This quarter",
}

/**
 * GET /api/export/[reportId]?format=pdf|markdown
 *
 * Exports the user's insight report as a styled PDF or markdown document.
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ reportId: string }> },
) {
  const { reportId } = await params
  const { userId: clerkUserId } = await auth()

  if (!clerkUserId) {
    return new NextResponse("Unauthorized", { status: 401 })
  }

  const format = req.nextUrl.searchParams.get("format") ?? "markdown"

  try {
    const db = getDatabase()

    const userRow = await db
      .select({ id: users.id })
      .from(users)
      .where(eq(users.clerkId, clerkUserId))
      .limit(1)
      .then((rows) => rows[0])

    if (!userRow) return new NextResponse("User not found", { status: 404 })

    const reportRow = await db
      .select()
      .from(reports)
      .where(and(eq(reports.id, reportId), eq(reports.userId, userRow.id)))
      .limit(1)
      .then((rows) => rows[0])

    if (!reportRow) return new NextResponse("Report not found", { status: 404 })

    const insightRows = await db
      .select({ section: insights.section, content: insights.content })
      .from(insights)
      .where(eq(insights.reportId, reportId))

    const insightMap = new Map<InsightSection, InsightContentInput>(
      insightRows.map((r) => [r.section as InsightSection, r.content as InsightContentInput]),
    )

    if (format === "markdown") {
      const markdown = buildMarkdown(reportRow.fileName, insightMap)
      return new NextResponse(markdown, {
        headers: {
          "Content-Type":        "text/markdown; charset=utf-8",
          "Content-Disposition": `attachment; filename="throughline-${reportRow.fileName.replace(/\.pdf$/i, "")}.md"`,
        },
      })
    }

    if (format === "pdf") {
      // For PDF export, return a print-optimized HTML page
      // The browser's native print-to-PDF handles the actual rendering
      const html = buildPrintHtml(reportRow.fileName, insightMap)
      return new NextResponse(html, {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      })
    }

    return new NextResponse("Invalid format. Use ?format=pdf or ?format=markdown", { status: 400 })
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    console.error("[export] Failed:", message)
    return new NextResponse("Export failed", { status: 500 })
  }
}

/* ── Markdown builder ── */

function buildMarkdown(
  fileName: string,
  insightMap: Map<InsightSection, InsightContentInput>,
): string {
  const sections: string[] = []

  sections.push(`# Throughline — Strengths Report\n`)
  sections.push(`_Source: ${fileName} · Generated by Throughline_\n`)
  sections.push("---\n")

  for (const section of SECTION_ORDER) {
    const content = insightMap.get(section)
    if (!content) continue

    const meta = SECTION_METADATA[section]

    sections.push(`## ${meta.title}`)
    sections.push(`**${content.headline}**\n`)
    sections.push(`${content.summary}\n`)

    if (content.evidence.length > 0) {
      sections.push("### Why this is true for you\n")
      for (const e of content.evidence) {
        sections.push(`- ${e}`)
      }
      sections.push("")
    }

    if (content.actions.length > 0) {
      sections.push("### Actions\n")
      for (const action of content.actions) {
        sections.push(
          `- **${ACTION_LABELS[action.when]}** (${action.why}): ${action.text}`,
        )
      }
      sections.push("")
    }

    if (content.watchOutFor) {
      sections.push(`> ⚠️ ${content.watchOutFor}\n`)
    }

    sections.push("---\n")
  }

  return sections.join("\n")
}

/* ── Print HTML builder ── */

function buildPrintHtml(
  fileName: string,
  insightMap: Map<InsightSection, InsightContentInput>,
): string {
  const sectionsHtml = SECTION_ORDER.map((section) => {
    const content = insightMap.get(section)
    if (!content) return ""

    const meta = SECTION_METADATA[section]

    const evidenceHtml = content.evidence.length > 0
      ? `<div class="evidence">
          <p class="label">Why this is true for you</p>
          <ul>${content.evidence.map((e) => `<li>${e}</li>`).join("")}</ul>
        </div>`
      : ""

    const actionsHtml = content.actions.length > 0
      ? `<div class="actions">
          <p class="label">Actions</p>
          ${content.actions.map((a) =>
            `<div class="action">
              <span class="when">${ACTION_LABELS[a.when]}</span>
              <span class="action-text">${a.text}</span>
              <span class="why">via ${a.why}</span>
            </div>`
          ).join("")}
        </div>`
      : ""

    const watchHtml = content.watchOutFor
      ? `<div class="watch-out"><strong>Watch out for:</strong> ${content.watchOutFor}</div>`
      : ""

    return `<section class="insight-section">
      <p class="section-label">${meta.title}</p>
      <h2>${content.headline}</h2>
      <p class="summary">${content.summary}</p>
      ${evidenceHtml}
      ${actionsHtml}
      ${watchHtml}
    </section>`
  }).join("")

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Throughline — ${fileName}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Georgia', serif; font-size: 12pt; line-height: 1.6; color: #1A1A1A; padding: 40px; max-width: 720px; margin: 0 auto; }
  h1 { font-size: 24pt; margin-bottom: 8px; }
  h2 { font-size: 16pt; margin-bottom: 8px; }
  .meta { color: #6B6B6B; font-size: 10pt; margin-bottom: 32px; }
  .insight-section { margin-bottom: 40px; padding-bottom: 40px; border-bottom: 1px solid #E5E1DB; }
  .section-label { font-size: 9pt; font-weight: bold; text-transform: uppercase; letter-spacing: 0.08em; color: #C4713A; margin-bottom: 8px; }
  .summary { color: #444; margin-bottom: 16px; }
  .label { font-size: 9pt; font-weight: bold; text-transform: uppercase; letter-spacing: 0.06em; color: #6B6B6B; margin-bottom: 8px; }
  .evidence { margin-bottom: 16px; }
  .evidence ul { padding-left: 16px; }
  .evidence li { margin-bottom: 6px; color: #444; }
  .actions { margin-bottom: 16px; }
  .action { display: flex; gap: 8px; margin-bottom: 8px; align-items: flex-start; }
  .when { font-size: 8pt; font-weight: bold; color: #C4713A; white-space: nowrap; margin-top: 2px; min-width: 80px; }
  .action-text { flex: 1; }
  .why { font-size: 8pt; color: #6B6B6B; white-space: nowrap; }
  .watch-out { background: #FAF8F4; border-left: 3px solid #D4962A; padding: 10px 12px; font-size: 10pt; color: #444; }
  @media print { body { padding: 20px; } .insight-section { page-break-inside: avoid; } }
</style>
</head>
<body>
  <h1>Your Strengths Report</h1>
  <p class="meta">Generated by Throughline from ${fileName}</p>
  ${sectionsHtml}
  <script>window.onload = () => window.print();</script>
</body>
</html>`
}
